# Generated by Django 4.2.30 on 2026-06-05 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('method', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('uzum_bank', 'Uzum Bank'), ('uzcard', 'Uzcard'), ('humo', 'Humo'), ('cash', 'Naqd')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', "To'landi"), ('failed', 'Xatolik'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
