# Generated by Django 4.2.30 on 2026-06-05 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['-rating'], 'verbose_name': 'Sotuvchi', 'verbose_name_plural': 'Sotuvchilar'},
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='marketplace.category'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
